name: Kubernetes E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  kubernetes-e2e:
    name: Kubernetes E2E Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    env:
      IMAGE_TAG: e2e
      KIND_CLUSTER: kind

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Set up KinD
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: ${{ env.KIND_CLUSTER }}
          version: v0.17.0

      - name: Build Docker images in parallel
        run: |
          SERVICES=(catalog ui cart orders checkout)
          for SERVICE in "${SERVICES[@]}"; do
            (
              echo "ðŸ”¹ Building $SERVICE..."
              yarn nx run $SERVICE:container \
                --tags public.ecr.aws/aws-containers/retail-store-sample-$SERVICE:${IMAGE_TAG}
            ) &
          done
          wait
          echo "âœ… All images built successfully."

      - name: Load Docker images into KinD
        run: |
          SERVICES=(catalog ui cart orders checkout)
          for SERVICE in "${SERVICES[@]}"; do
            echo "ðŸš€ Loading $SERVICE into KinD..."
            kind load docker-image public.ecr.aws/aws-containers/retail-store-sample-$SERVICE:${IMAGE_TAG} --name $KIND_CLUSTER
          done

      - name: Deploy with Helmfile
        shell: bash
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          NODE_PORT=30000 helmfile apply -f src/app/helmfile.yaml --wait --skip-diff-on-install
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/owner=retail-store-sample --timeout=180s || exit_code=$?

      - name: Run E2E tests
        shell: bash
        run: |
          bash scripts/e2e-kind.sh

      - name: Cleanup Docker
        run: docker system prune --all --force